config/routes.rb
LandingPage::Application.routes.draw do

  root to: 'emails#new'

  match 'danke', to: 'pages#danke'
  match 'fehler', to: 'pages#fehler'
  match 'beispielrechnung', to: 'pages#beispielrechnung'

  resources :emails
end

app/models/email.rb
class Email
  include Mongoid::Document
  include Mongoid::Timestamps

  field :salutation
  field :title
  field :name
  field :company
  field :position
  field :phone
  field :email
  field :notes

  validates_presence_of :name, :company, :email
  validates_format_of :email, with: /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  respond_to :html

  expose(:email)

  def create
    if email.save
      Mailer.lead_notification(email).deliver
      respond_with(email, location: root_path(id: email.id))
    else
      respond_with(email)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  expose(:email)

  def danke
    render layout: false
  end

  def fehler
    render layout: false
  end

  def beispielrechnung
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>1000jobboersen.de</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script>
    !window.jQuery && document.write('<script src="/javascripts/jquery-1.4.3.min.js"><\/script>');
  </script>

  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic', media: 'all', rel: 'stylesheet' -%>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/pages/beispielrechnung.html.erb
<div id="danke" style="height:502px; width:593px; position:inherit; background:url('<%= asset_path 'rechn_bg.png' %>') no-repeat left bottom;">
  <div style="height:410px; width:533px; left:30px; top:40px; position:relative;">
    <!-- tab here / START -->
        <%= image_tag 'beispiel.jpg', width: 252, height: 30, border: 0 %>

<table width="530" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="2" style="padding-bottom:20px; padding-top:10px; line-height:14px;">1000jobboersen.de erstellt für jede Stellenanzeige ein individuelles Angebot mit einer optimal auf die Vankanz abgestimmten Kombination von Stellenbörsen. Die folgende Beispielrechnung soll Ihnen lediglich verdeutlichen, wie der Aktions-Bonus verrechnet wird.</td>
  </tr>
  <tr>
    <td width="421" bgcolor="#F0F0F0" style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Individuelle Stellenbörsen-Kombination<br />(Marktpreis bei Selbstkauf: 4.795 €)</td>
    <td width="109" bgcolor="#F0F0F0" align="right" style="padding:5px;">2.349 €</td>
  </tr>
  <tr>
    <td style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Reichweitensteigerung oder Social Media</td>
    <td align="right" style="padding:5px;">100 €</td>
  </tr>
  <tr>
    <td bgcolor="#F0F0F0" style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Anzeigen-Layout</td>
    <td bgcolor="#F0F0F0" align="right" style="padding:5px;">150 €</td>
  </tr>
  <tr>
    <td style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Titel- und Textoptimierung</td>
    <td align="right" style="padding:5px;">150 €</td>
  </tr>
  <tr>
    <td bgcolor="#F0F0F0" style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Lektorat, AGG-Sicherheit</td>
    <td bgcolor="#F0F0F0" align="right" style="padding:5px;">50 €</td>
  </tr>
  <tr>
    <td style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Anzeigenveröffentlichung und Betreuung über die gesamte Laufzeit</td>
    <td align="right" style="padding:5px;">100 €</td>
  </tr>
  <tr>
    <td bgcolor="#F0F0F0" style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Refresh</td>
    <td bgcolor="#F0F0F0" align="right" style="padding:5px;">60 €</td>
  </tr>
  <tr>
    <td style="padding-left:5px; padding-top:2px; padding-bottom:2px;"><strong>Auftragswert</strong></td>
    <td align="right" style="padding:5px;"><strong>2.959 €</strong></td>
  </tr>
  <tr>
    <td bgcolor="#F0F0F0" style="padding-left:5px; padding-top:2px; padding-bottom:2px;">Bonus 2 x 500 €</td>
    <td bgcolor="#F0F0F0" align="right" style="padding:5px;">- 1.000 €</td>
  </tr>
  <tr>
    <td style="padding-left:5px; padding-top:10px; padding-bottom:2px;"><b><u>Ihr Preis</u></b></td>
    <td align="right" style="padding:5px;"><b><u>1.959 €</u></b></td>
  </tr>
</table>

<!-- tab here / ENDE -->
  <div style="height:40px; width:268px; left:125px; top:10px; position:relative;">
    <%= link_to root_path do %>
      <%= image_tag 'danke_close.png', border: 0, width: 263, height: 35 %>
    <% end %>
  </div>
  </div>
</div>

app/views/pages/danke.html.erb
<div id="danke" style="height:260px; width:436px; position:inherit; background:url('<%= asset_path 'danke.png' %>') no-repeat left bottom;">
  <div style="height:40px; width:268px; left:82px; top:180px; position:relative;">
    <a href="http://www.1000jobboersen.de/" target="_self"><img src="<%= asset_path 'danke_close.jpg' %>" border="0" width="268" height="40"></a>
  </div>
</div>

app/views/pages/fehler.html.erb
<div id="danke" style="height:210px; width:436px; position:inherit; background:url('<%= asset_path 'fehler.png' %>') no-repeat left bottom;">
  <div style="height:40px; width:268px; left:82px; top:150px; position:relative;">
    <%= link_to root_path, id: 'fehler_close' do %>
      <%= image_tag 'danke_close.jpg', border: 0, width: 268, height: 40 %>
    <% end %>
  </div>
  <div style="height:60px; width:370px; left:30px; top:30px; position:relative; color:#333333;">
  </div>
</div>

app/views/pages/index.html.erb
<% if params[:sending] %>
  <%= link_to '', fehler_path, id: 'autostart' %>
<% else %>
  <%= link_to 'test', danke_path, id: 'autostart' %>
<% end %>

<div id="page-container" class="page-container">

  <div id="page-header" class="page-header">
    <div id="logo" class="logo">
      <%= link_to 'http://www.1000jobboersen.de' do %>
        <%= image_tag '1000jb_logo.jpg', width: 380, height: 56, border: 0 %>
      <% end %>
    </div>
    <div id="hotline" class="hotline">
      <%= image_tag 'hotline.jpg', width: 222, height: 68, border: 0 %>
    </div>
  </div>
  <div id="page-content" class="page-content">

    <!-- formular container /Start-->
    <div id="page-form-top-container" class="page-form-top-container">

  <div id="page-form-top" class="page-form-top typo"></div>
  <div id="page-form-txt" class="page-form-txt">
    <%= image_tag 'form_bg_txt.jpg', border: 0, style: 'padding-left:10px; padding-top:10px;' %>
  </div>
  <div id="page-form-mid" class="page-form-mid typo">

<%= form_tag emails_path, name: 'angebot' do %>
<table width="442" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td colspan="3" style="padding-top: 10px;padding-bottom:10px; line-height:13px;">
  Damit wir Sie beraten können, bitten wir Sie um die folgenden Angaben. Unsere Spezialisten werden sich innerhalb eines Werktages bei Ihnen melden.
  <!--
    <br />
    Falls Sie bereits eine Stellenanzeige haben, zu der Sie ein Angebot erhalten möchten, können Sie diese mit der Upload-Funktion direkt an uns senden. -->
    </td>
  </tr>
  <tr>
    <td width="115" style="padding-top:10px;">Anrede:<br />
    <select name="anrede" id="anrede" class="form skurz" onclick="MM_changeProp('anrede','','backgroundColor','#fff'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');">
      <option value="Herr" selected="selected">Herr</option>
      <option value="Frau">Frau</option>
    </select>
    </td>
    <td width="115" style="padding-top:10px;">Titel:<br />
    <select name="titel" id="titel" class="form skurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fff'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');">
      <option value="" selected="selected">&nbsp;</option>
      <option value="dr.">Dr.</option>
      <option value="prof.">Prof.</option>
      <option value="dipl.ing.">Dipl.Ing.</option>
    </select>
    </td>
    <td width="216" style="padding-top:10px;">* Name, Vorname:<br />
    <input name="name" id="name" type="text" class="form kurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fff'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');" onfocus="this.value = ''" /></td>
  </tr>
  <tr>
    <td colspan="2" style="padding-top:10px;">* Ihr Unternehmen:<br />
    <input name="unternehmen" type="text" id="unternehmen" class="form kurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fff'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');" onfocus="this.value = ''" /></td>
    <td style="padding-top:10px;">Position:<br />
      <input name="position" id="position" type="text" class="form kurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fff'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');" onfocus="this.value = ''" /></td>
  </tr>
  <tr>
    <td colspan="2" style="padding-top:10px;">Vorwahl + Rufnummer:<br />
    <input type="text" name="telefon" id="telefon" class="form kurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fff'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');" onfocus="this.value = ''" /></td>
    <td style="padding-top:10px;">* E-Mail Adresse:<br />
      <input type="text" name="email" id="email" class="form kurz" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fff'); MM_changeProp('mitteilung','','backgroundColor','#fccd7f');" onfocus="this.value = ''" /></td>
    </tr>
  <tr>
    <td colspan="3" style="padding-top:10px;">Mitteilungen (z.B. bevorzugte Anrufzeit)<br />
    <textarea name="mitteilung" id="mitteilung" value="Ihre Mitteilung" class="form lang" rows="2" onclick="MM_changeProp('anrede','','backgroundColor','#fccd7f'); MM_changeProp('titel','','backgroundColor','#fccd7f'); MM_changeProp('name','','backgroundColor','#fccd7f'); MM_changeProp('unternehmen','','backgroundColor','#fccd7f'); MM_changeProp('position','','backgroundColor','#fccd7f'); MM_changeProp('telefon','','backgroundColor','#fccd7f'); MM_changeProp('email','','backgroundColor','#fccd7f'); MM_changeProp('mitteilung','','backgroundColor','#fff');" onfocus="this.value = ''" /></textarea></td>
    </tr>
  <tr>
    <td colspan="3" style="padding-top:15px; padding-bottom:15px;">
    <!--<input name="send" type="hidden" class="form kurz" id="send" value="sending" />-->
    
    <input type="image" border="0" name="senden" alt="Angebot anfordern" src="<%= asset_path 'btn_senden.jpg' %>">
    <!--<a href="danke.php" id="various2"><img src="img/btn_senden.jpg" border="0" alt="Angebot anfordern" /></a>-->
    
    </td>
    </tr>
</table>
<% end %>
<!-- Formular ENDE -->
    
    </div>
  <div id="page-form-bottom" class="page-form-bottom typo"></div>  
    <span style="padding-left:20px;">* - Pflichtfelder</span>
    </div>
    <!-- formular container /Ende-->
    
    <div id="teaser" class="teaser">
        
    <div id="angebot" class="angebot">
    
      <ul style="margin-left:-10px; padding-top:50px;">
          <li>Individuelle Auswahl der relevanten Jobbörsen,<br />Nischenportale und Social Media-Kanäle</li>
          <li>Kostenfreie Beratung durch unsere Spezialisten</li>
          <li>Professionelles Layout, Titel- und Textoptimierung</li>
          <li>Anzeigen-Veröffentlichung und Refresh</li>
          <li>Bestes Preis-Leistungsverhältnis</li>
          <li>500 Euro Wertbonus je 1.000 Euro Anzeigenwert</li>
          <li>"Für bis zu 5 Stellenanzeigen</li>
        </ul>
        <br /><br /><br />
        <a href="beispielrechnung.php" id="various1" style="font-size:14px; padding-left:20px;"><b>&gt; Beispielrechnung</b></a>
<br />
<a href="ahttp://www.1000jobboersen.de/wertsteigerung/angebotsbedingungen.pdf" target="_blank" style="font-size:14px; padding-left:30px;"><b>Angebotsbedingungen</b></a>
        
    </div>
    
    </div>
    
  </div>
    
</div>

<div id="page-footer" class="page-footer">

<div style="height:98px; width:80px; position:inherit; float:right; margin-bottom:-20px; margin-right:10px;">
<a href="http://karriere.de/"><img src="http://1000jobboersen.de/images/logos/faircompany.png" width="77" height="99" border="0" alt="karriere.de" /></a>
</div>

<div style="height:60px; width:330px; background:url('http://1000jobboersen.de/stylesheets/_img/bg-jobfinder.png') no-repeat left bottom; padding:30px 0px 10px 95px;; position:inherit; float:right;">
<span style="color:#1e518b; font-size:20px; font-weight:bold;">Unser Partnerportal:<br /></span>
<a href="http://www.jobboersenfinder.de/" style="color:#313131; font-size:24px; font-weight:bold;">www.jobboersenfinder.de</a>
</div>

<div id="footer-menu" class="footer-menu">
<a href="http://1000jobboersen.de/kontakt" style="padding-right:18px;">Kontakt</a> - 
<a href="http://1000jobboersen.de/agb" style="padding-right:18px; padding-left:18px;">AGB</a> - 
<a href="http://1000jobboersen.de/impressum" style="padding-left:18px;">Impressum</a>
</div>
 
</div>
<div id="page-copy" class="page-copy">
© 2011 - HR New Media GmbH, Tauentzienstraße 14 | 10789 Berlin, 1000jobboersen.de | 
Sitz: Berlin | HRB 114159 B - Amtsgericht Berlin-Charlottenburg | 
Geschäftsführer: Florian Behn, Benjamin Pochhammer
</div>